import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Briefcase, ClipboardList, Home, PlusCircle, Settings } from 'lucide-react';
import { buildSegmentPlan, hasSegmentErrors, type Segment } from './segments';
import './styles.css';

// Platform mode is selected at build time by VITE_STUDIO_PLATFORM_MODE.
const platformMode = import.meta.env.VITE_STUDIO_PLATFORM_MODE === 'platform';
const appUrl = import.meta.env.VITE_APP_PUBLIC_URL ?? 'https://studio.librechat.online';
type Page = 'dashboard' | 'projects' | 'new' | 'jobs' | 'settings';
type User = { email: string; role: string };
type Project = { id: string; title: string; description: string | null; created_at: string; updated_at: string; archived_at: string | null };
type Credential = { id: string; provider: 'elevenlabs' | 'openai'; label: string; status: string; masked_value?: string; active_version?: number };
type Audit = { id: string; type: string; created_at: string };
const nav: { id: Page; label: string; icon: typeof Home }[] = [
  { id: 'dashboard', label: 'Панель', icon: Home }, { id: 'projects', label: 'Проекты', icon: Briefcase },
  { id: 'new', label: 'Новая транскрибация', icon: PlusCircle }, { id: 'jobs', label: 'Задачи', icon: ClipboardList }, { id: 'settings', label: 'Настройки', icon: Settings },
];
const demoProjects = ['Интервью продукта — демо', 'Подкаст о локализации — демо', 'Исследование звонков — демо'];
const demoJobs = [{ title: 'Демо: ожидание серверной очереди', state: 'Прототип' }, { title: 'Демо: проверка сегментов', state: 'UI-only' }];
async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const res = await fetch(`/api${path}`, { ...options, credentials: 'same-origin', headers: { 'content-type': 'application/json', ...(options.headers ?? {}) } });
  if (!res.ok) throw new Error(res.status === 429 ? 'Слишком много попыток. Попробуйте позже.' : 'Операция не выполнена. Проверьте данные и повторите.');
  return res.json();
}
function NewTranscription() {
  const [file, setFile] = useState<File | null>(null); const [segments, setSegments] = useState<Segment[]>([{ id: crypto.randomUUID(), title: '', end: '' }]);
  const plan = useMemo(() => buildSegmentPlan(segments), [segments]); const invalid = hasSegmentErrors(segments);
  return <section className="card wide"><p className="eyebrow">Локально в браузере</p><h2>Новая транскрибация</h2><p className="notice">Файл не загружается на сервер. Provider calls, Google Drive/Docs и серверные задачи появятся позже.</p><label className="drop">Выберите audio/video файл<input type="file" accept="audio/*,video/*" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label>{file && <dl className="meta"><dt>Файл</dt><dd>{file.name}</dd><dt>Размер</dt><dd>{(file.size / 1024 / 1024).toFixed(2)} MB</dd><dt>Тип</dt><dd>{file.type || 'не указан браузером'}</dd></dl>}<div className="builder"><h3>Сегменты будущих документов</h3>{segments.map((s, i) => <div className="segment" key={s.id}><strong>Часть {i + 1}</strong><label>Название Google Doc (прототип)<input value={s.title} onChange={(e) => setSegments(v => v.map(x => x.id === s.id ? { ...x, title: e.target.value } : x))} placeholder={`Часть ${i + 1}`} /></label>{i < segments.length - 1 ? <label>Конец части<input value={s.end} onChange={(e) => setSegments(v => v.map(x => x.id === s.id ? { ...x, end: e.target.value } : x))} placeholder="MM:SS" aria-invalid={Boolean(plan[i]?.error)} /></label> : <span className="pill">До конца записи</span>}<button type="button" onClick={() => setSegments(v => [...v, { id: crypto.randomUUID(), title: '', end: '' }])}>Добавить часть</button>{plan[i]?.error && <p className="error">{plan[i].error}</p>}</div>)}</div><ol className="timeline">{plan.map(p => <li key={p.index}><b>{p.title}</b><span>{p.start} → {p.endLabel}</span></li>)}</ol><button className="primary" disabled={!file || invalid}>Подготовить черновик задачи</button></section>;
}
function StaticShell() {
  const [page, setPage] = useState<Page>('dashboard');
  return <div className="shell"><aside><div className="brand">Studio PWA<span>UI foundation</span></div><nav>{nav.map(({ id, label, icon: Icon }) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}><Icon size={18}/>{label}</button>)}</nav></aside><main>{page === 'dashboard' && <section className="hero"><p className="eyebrow">Русскоязычная Studio</p><h1>Панель готова к установке</h1><p>Это статический PWA-фундамент: app shell и прототипы будущих сценариев без входа, API, транскрибации и интеграций.</p><button className="primary" onClick={() => setPage('new')}>Создать черновик</button></section>}{page === 'projects' && <section className="grid"><h2>Проекты</h2>{demoProjects.map(p => <article className="card" key={p}><span className="tag">Демо-данные</span><h3>{p}</h3><p>Клиентский прототип, не связан с Drive или manifest.</p></article>)}</section>}{page === 'new' && <NewTranscription />}{page === 'jobs' && <section className="grid"><h2>Задачи</h2>{demoJobs.map(j => <article className="card" key={j.title}><span className="tag">{j.state}</span><h3>{j.title}</h3><p>Реальная очередь и provider processing ещё не подключены.</p></article>)}</section>}{page === 'settings' && <section className="card wide"><h2>Настройки</h2><p>Публичный URL приложения:</p><code>{appUrl}</code><p className="notice">Статический режим не обращается к `/api` и не требует PostgreSQL, Redis или секретов.</p></section>}</main></div>;
}
function Login({ onLogin }: { onLogin: (u: User, csrf: string) => void }) {
  const [bootstrap, setBootstrap] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api<{ bootstrap_required: boolean }>('/auth/bootstrap-status').then(r => setBootstrap(r.bootstrap_required)).catch(() => setError('API временно недоступен.')); }, []);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(''); const fd = new FormData(e.currentTarget); try { const ctx = await api<{ login_csrf_token: string }>('/auth/login-context', { method: 'POST' }); const r = await api<{ user: User; csrf_token: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ email: fd.get('email'), password: fd.get('password'), login_csrf_token: ctx.login_csrf_token }) }); onLogin(r.user, r.csrf_token); } catch (err) { setError(err instanceof Error ? err.message : 'Не удалось войти.'); } }
  if (bootstrap) return <main className="auth"><section className="card"><h1>Требуется первичная настройка</h1><p className="notice">Публичной формы администратора нет. Обратитесь к оператору, чтобы выполнить bootstrap-admin команду на сервере.</p></section></main>;
  return <main className="auth"><form className="card login" onSubmit={submit}><p className="eyebrow">Studio account</p><h1>Вход</h1><label>Email<input name="email" type="email" autoComplete="username" required /></label><label>Пароль<input name="password" type="password" autoComplete="current-password" required /></label><button className="primary">Войти</button>{error && <p className="error">{error}</p>}</form></main>;
}
function ProjectCard({ project, csrf, onCsrf, onReload }: { project: Project; csrf: string; onCsrf: (csrf: string) => void; onReload: () => void }) {
  const [editing, setEditing] = useState(false); const [error, setError] = useState('');
  async function safeMutate<T>(path: string, options: RequestInit): Promise<T> {
    try { return await api<T>(path, { ...options, headers: { 'x-csrf-token': csrf, ...(options.headers ?? {}) } }); }
    catch { const refreshed = await api<{ csrf_token: string }>('/auth/csrf', { method: 'POST' }); onCsrf(refreshed.csrf_token); return api<T>(path, { ...options, headers: { 'x-csrf-token': refreshed.csrf_token, ...(options.headers ?? {}) } }); }
  }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(''); const fd = new FormData(e.currentTarget); try { await safeMutate(`/projects/${project.id}`, { method: 'PATCH', body: JSON.stringify({ title: fd.get('project_title'), description: fd.get('project_description') }) }); setEditing(false); onReload(); } catch (err) { setError(err instanceof Error ? err.message : 'Ошибка'); } }
  async function archive() { setError(''); try { await safeMutate(`/projects/${project.id}/archive`, { method: 'POST' }); onReload(); } catch (err) { setError(err instanceof Error ? err.message : 'Ошибка'); } }
  return <article className="card project-card"><span className="tag">Project</span>{editing ? <form className="project-form" onSubmit={save}><label>Название<input name="project_title" defaultValue={project.title} maxLength={160} required /></label><label>Описание<textarea name="project_description" defaultValue={project.description ?? ''} maxLength={2000} /></label><div className="actions"><button className="primary">Сохранить</button><button type="button" onClick={() => setEditing(false)}>Отмена</button></div></form> : <><h3>{project.title}</h3><p>{project.description || 'Описание пока не добавлено.'}</p><small>Обновлён: {new Date(project.updated_at).toLocaleString('ru-RU')}</small><div className="actions"><button onClick={() => setEditing(true)}>Редактировать</button><button onClick={archive}>Архивировать</button></div></>}{error && <p className="error">{error}</p>}</article>;
}
function ProjectsPage({ csrf, onCsrf }: { csrf: string; onCsrf: (csrf: string) => void }) {
  const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); api<{ projects: Project[] }>('/projects').then(r => setProjects(r.projects)).catch(err => setError(err instanceof Error ? err.message : 'Не удалось загрузить проекты.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  async function safeMutate<T>(path: string, options: RequestInit): Promise<T> {
    try { return await api<T>(path, { ...options, headers: { 'x-csrf-token': csrf, ...(options.headers ?? {}) } }); }
    catch { const refreshed = await api<{ csrf_token: string }>('/auth/csrf', { method: 'POST' }); onCsrf(refreshed.csrf_token); return api<T>(path, { ...options, headers: { 'x-csrf-token': refreshed.csrf_token, ...(options.headers ?? {}) } }); }
  }
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(''); const form = e.currentTarget; const fd = new FormData(form); try { await safeMutate('/projects', { method: 'POST', body: JSON.stringify({ title: fd.get('project_title'), description: fd.get('project_description') }) }); form.reset(); load(); } catch (err) { setError(err instanceof Error ? err.message : 'Не удалось создать проект.'); } }
  return <section className="wide"><div className="section-head"><div><p className="eyebrow">Workspace</p><h2>Проекты</h2></div><button onClick={load}>Обновить</button></div><form className="card project-form compact" onSubmit={create}><h3>Новый проект</h3><label>Название<input name="project_title" placeholder="Например: интервью продукта" maxLength={160} required /></label><label>Описание<textarea name="project_description" placeholder="Краткая заметка (необязательно)" maxLength={2000} /></label><button className="primary">Создать проект</button></form>{loading && <p className="notice">Загружаем проекты…</p>}{error && <p className="error">{error}</p>}{!loading && !error && projects.length === 0 && <p className="notice">У вас пока нет проектов. Создайте первый workspace выше.</p>}{!loading && !error && projects.length > 0 && <div className="grid">{projects.map(p => <ProjectCard key={p.id} project={p} csrf={csrf} onCsrf={onCsrf} onReload={load} />)}</div>}</section>;
}

function SettingsPage({ user, csrf, onCsrf, onLogout }: { user: User; csrf: string; onCsrf: (csrf: string) => void; onLogout: () => void }) {
  const [credentials, setCredentials] = useState<Credential[]>([]); const [events, setEvents] = useState<Audit[]>([]); const [error, setError] = useState('');
  const load = () => { api<{ credentials: Credential[] }>('/credentials').then(r => setCredentials(r.credentials)); api<{ events: Audit[] }>('/audit-events').then(r => setEvents(r.events)); };
  useEffect(load, []);
  async function safeMutate<T>(path: string, options: RequestInit): Promise<T> {
    try { return await api<T>(path, { ...options, headers: { 'x-csrf-token': csrf, ...(options.headers ?? {}) } }); }
    catch { const refreshed = await api<{ csrf_token: string }>('/auth/csrf', { method: 'POST' }); onCsrf(refreshed.csrf_token); return api<T>(path, { ...options, headers: { 'x-csrf-token': refreshed.csrf_token, ...(options.headers ?? {}) } }); }
  }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const fd = new FormData(e.currentTarget); try { await safeMutate('/credentials', { method: 'POST', body: JSON.stringify({ provider: fd.get('provider'), label: fd.get('credential_label'), raw_value: fd.get('credential_raw_value') }) }); e.currentTarget.reset(); load(); } catch (err) { setError(err instanceof Error ? err.message : 'Ошибка'); } }
  async function replace(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const fd = new FormData(e.currentTarget); const id = String(fd.get('credential_id') ?? ''); const selected = credentials.find(c => c.id === id); if (!selected) return setError('Выберите credential для замены.'); try { await safeMutate(`/credentials/${id}/replace`, { method: 'POST', body: JSON.stringify({ provider: selected.provider, label: selected.label, raw_value: fd.get('replacement_credential_raw_value') }) }); e.currentTarget.reset(); load(); } catch (err) { setError(err instanceof Error ? err.message : 'Ошибка'); } }
  const action = async (path: string, method = 'POST') => { setError(''); try { await safeMutate(path, { method }); load(); } catch (err) { setError(err instanceof Error ? err.message : 'Ошибка'); } };
  return <section className="card wide"><h2>Настройки аккаунта</h2><p>Аккаунт: <b>{user.email}</b> ({user.role})</p><button onClick={onLogout}>Выйти</button><h3>BYOK credentials</h3><p className="notice">Ключи отправляются только same-origin API, не сохраняются в браузере и никогда не отображаются обратно.</p><form className="inline" onSubmit={save} autoComplete="off"><select name="provider"><option value="elevenlabs">ElevenLabs</option><option value="openai">OpenAI</option></select><input name="credential_label" autoComplete="off" placeholder="Метка" required /><input name="credential_raw_value" type="password" autoComplete="new-password" spellCheck={false} data-1p-ignore="true" data-lpignore="true" data-bwignore="true" placeholder="Новый ключ" required /><button className="primary">Создать</button></form><form className="inline" onSubmit={replace} aria-label="Заменить credential" autoComplete="off"><select name="credential_id" required><option value="">Выберите credential</option>{credentials.map(c => <option key={c.id} value={c.id}>{c.provider} · {c.label} · {c.masked_value}</option>)}</select><input name="replacement_credential_raw_value" type="password" autoComplete="new-password" spellCheck={false} data-1p-ignore="true" data-lpignore="true" data-bwignore="true" placeholder="Новый ключ для замены" required /><button className="primary">Заменить</button></form>{error && <p className="error">{error}</p>}<div className="grid">{credentials.map(c => <article className="card" key={c.id}><span className="tag">{c.provider}</span><h3>{c.label}</h3><p>{c.status} · v{c.active_version ?? '—'} · {c.masked_value}</p><button onClick={() => action(`/credentials/${c.id}/revoke`)}>Отозвать</button><button onClick={() => action(`/credentials/${c.id}`, 'DELETE')}>Удалить</button></article>)}</div><h3>События безопасности</h3><ul>{events.map(e => <li key={e.id}>{e.type} · {new Date(e.created_at).toLocaleString('ru-RU')}</li>)}</ul></section>;
}
function PlatformShell() {
  const [page, setPage] = useState<Page>('dashboard'); const [user, setUser] = useState<User | null>(null); const [csrf, setCsrf] = useState('');
  useEffect(() => { api<{ authenticated: boolean; user: User }>('/auth/session').then(r => { setUser(r.user); return api<{ csrf_token: string }>('/auth/csrf', { method: 'POST' }); }).then(r => setCsrf(r.csrf_token)).catch(() => undefined); }, []);
  if (!user) return <Login onLogin={(u, t) => { setUser(u); setCsrf(t); }} />;
  const logout = async () => { let token = csrf; if (!token) { const refreshed = await api<{ csrf_token: string }>('/auth/csrf', { method: 'POST' }); token = refreshed.csrf_token; setCsrf(token); } await api('/auth/logout', { method: 'POST', headers: { 'x-csrf-token': token } }).catch(() => undefined); setUser(null); setCsrf(''); };
  return <div className="shell"><aside><div className="brand">Studio PWA<span>Platform core</span></div><nav>{nav.map(({ id, label, icon: Icon }) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}><Icon size={18}/>{label}</button>)}</nav></aside><main>{page === 'dashboard' && <section className="hero"><p className="eyebrow">Русскоязычная Studio</p><h1>Панель аккаунта готова</h1><p>Подключены вход, серверная сессия и BYOK-настройки. Транскрибация, загрузки, Google и очереди остаются прототипом.</p><button className="primary" onClick={() => setPage('new')}>Создать черновик</button></section>}{page === 'projects' && <ProjectsPage csrf={csrf} onCsrf={setCsrf} />}{page === 'new' && <NewTranscription />}{page === 'jobs' && <section className="grid"><h2>Задачи</h2>{demoJobs.map(j => <article className="card" key={j.title}><span className="tag">{j.state}</span><h3>{j.title}</h3><p>Реальная очередь и provider processing ещё не подключены.</p></article>)}</section>}{page === 'settings' && <SettingsPage user={user} csrf={csrf} onCsrf={setCsrf} onLogout={logout} />}</main></div>;
}
export default function App({ mode = platformMode ? 'platform' : 'static' }: { mode?: 'static' | 'platform' } = {}) { return mode === 'platform' ? <PlatformShell /> : <StaticShell />; }
